server:
  port: 12000
spring:
  application:
    name: huahua-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaoweien/huahua_dev.git
  rabbitmq:
    host: 192.168.234.131
management: #暴露触发信息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh